# Prefer 256 colors / truecolor
set -g default-terminal "xterm-256color"
set -as terminal-overrides ",*:Tc"



set-option -g mouse on # activates mouse

				# start windows at 1 and not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

				# split panes in cwd (rebinds split binds to current path)
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

				# cycle windows
bind -n M-H previous-window 	# Alt + Shift + H
bind -n M-L next-window			# Alt + Shift + L

				# prefix 
unbind C-b 
set -g prefix C-Space
bind C-Space send-prefix

# Tell TPM to install plugins into the shared Exegol mount
set-environment -g TMUX_PLUGIN_MANAGER_PATH "/opt/my-resources/setup/tmux/plugins"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible' 

# Omarchy tmux theme plugin (we'll force Osaka Jade manually)
set -g @theme "osaka"
set -g @theme_variant "jade"

# If you DON'T have a Nerd Font, set this to '1' to avoid icon glyphs
set -g @theme_no_patched_font '0'

set -g @plugin 'joaofelipegalvao/omarchy-tmux'



# TPM init (must stay at the bottom)
run-shell -b "/opt/my-resources/setup/tmux/plugins/tpm/tpm"
